### ISSUE TITLE
Null reference breaking inspector on ScreenManagerEditor after upgrading to Unity 2018.3

### ISSUE THREAD

**Issue by DanielPhk** [Xerios/ScreenManager#12]
`GUI.skin.FindStyle("TL tab mid")` returns null. Other calls to FindStyle return null as well, not sure if Unity changed anything regarding GUIStyles...

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.GUILayoutEntry.ApplyStyleSettings (UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/Modules/IMGUI/LayoutEntry.cs:67)
UnityEngine.GUILayoutGroup.ApplyStyleSettings (UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/Modules/IMGUI/LayoutGroup.cs:87)
UnityEngine.GUILayoutEntry.set_style (UnityEngine.GUIStyle value) (at C:/buildslave/unity/build/Modules/IMGUI/LayoutEntry.cs:31)
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at C:/buildslave/unity/build/Modules/IMGUI/GUILayoutUtility.cs:303)
UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Modules/IMGUI/GUILayout.cs:257)
UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Modules/IMGUI/GUILayout.cs:249)
ScreenMgr.ScreenManagerEditor.OnInspectorGUI () (at Assets/Plugins/ScreenManager-master/ScreenManager/Editor/ScreenManagerEditor.cs:193)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1625)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by cluetivity** [comment]
Hi, 
I'm having similar issues with Unity 2018.3.1f1.
Lots of errors in Editor and you don't see the list of Screens anymore.

Will try Unity 2018.3.3 now.

Edit: no difference with Unity 2018.3.3. Help is highly appreciated.

**Comment by Xerios** [comment]
I'll give it a look this afternoon and push a fix

**Comment by cluetivity** [comment]
thank you so much. did you have a chance to look into it?

**Comment by Xerios** [comment]
I completely got side-tracked, thanks for the weekend reminder. I pushed the fix 👍

**Comment by DanielPhk** [comment]
Awesome, thank you very much!
