### ISSUE TITLE
Support custom dimension for each screen

### ISSUE THREAD

**Issue by takaaptech** [Xerios/ScreenManager#2]
Hi, currently i am working on vertical shooting game (think of sky force or other galaxy shooter game)
I think with the power of this lib, if we support custom with or height of each screen, and then we support screen scrolling (vertical or horizontal ), we will have awesome screen editor for building platformer or galaxy fighter game?
What do you think about that feature? Thank so much@

**Comment by Xerios** [comment]
I'm pretty sure using Unity's Canvas Scaler component you can achieve that result. Check out Canvas Scaler for different screen width/height and Scrollview for scrolling. Unless you are talking about something completely different?

**Comment by takaaptech** [comment]
I mean we can design multi "screen" size by size using our  "spread" function, and then we can combine those screens into an endless verticle or horizontal screen
I mean we will have a scene editor, like this:
(https://www.youtube.com/watch?v=WiVURJTUgNo)

**Comment by Xerios** [comment]
![image](https://cloud.githubusercontent.com/assets/181384/24920013/e8b5868e-1ee5-11e7-8909-ebe79d0f9d92.png)

Something like this?

I've committed the change, tell me if it looks alright 👍

**Comment by takaaptech** [comment]
Great! That is exactly what I mean! Now we will find a way to stack the screen and scroll the screen list by horizontal or vertical direction, (something as simple as scroll a pdf document page by page) Can you support that feature?

**Comment by Xerios** [comment]
I'm confused, care to elaborate? It sounds like you're asking for a game related feature which has nothing to do with menus..

**Comment by takaaptech** [comment]
Yeah! This feature focuses on design game scene only!
For example, in a flight shooter game, we have 10 scenes with the same width and difference height. And after design enemy waves, decoration for each scene, we can put it by vertical and scroll down 10 scenes from bottom to top to make a vertical shooting game!
That my thought so far!

**Comment by Xerios** [comment]
You would be better off if you use separate scenes for this, once you reach the end of a certain screen you can simply do a LoadLevelAdditive and load the next screen, then move that screen to the top most position of the existing scene.

**Comment by takaaptech** [comment]
That makes sense! Thank so much for the advice!
