### ISSUE TITLE
Create Navigation between Screen by Node Editor

### ISSUE THREAD

**Issue by takaaptech** [Xerios/ScreenManager#3]
Hi,
I think you can write simple Node editor (e.x using https://github.com/Seneral/Node_Editor) to create navigation between screen. My idea is:
- Each screen is a node, each node link with other Node via link, all they make Screen Graph
- Screen Graph have Start Node (Equals to Set Default function)
- Each Node have one input and multi output (each output will generate one button for easy demo and navigation)
- When we create new node on Screen Graph, ScreenManager will create new screen object as child of Screen Manager object.

What do you think about this idea?

**Comment by Xerios** [comment]
Sounds like a nice idea!

It would fit nicely if used as an additional layer on top of ScreenManager ( leaving the ScreenManager as a core library, while Screen Graphs will extend the functionality ). 
If you come up with something nice, feel free to contribute ! I'll gladly integrate such feature :)

**Comment by Xerios** [comment]
Hit me up if you have anything to show. I'll close this thread for now.
