### ISSUE TITLE
What function to start the game in Game Screen

### ISSUE THREAD

**Issue by takaaptech** [Xerios/ScreenManager#4]
Hi,
I have Ingame screen that extend BaseScreen. I wonder what is best function to init and start game logic? (For example we will init level and start update loop )
Is this: OnAnimationInEnd ? 

Thank so much!

**Comment by Xerios** [comment]
It all depends on how you did your game, there are no specific rules. Although like I said previously, having game not part of ScreenManager would be the best way to go. In that case, you hide all screens and start the game, simple as that!

**Comment by takaaptech** [comment]
Thank so much!
