### ISSUE TITLE
Any back button functionality?

### ISSUE THREAD

**Issue by hex** [Xerios/ScreenManager#9]
Hi there, is there any back button functionality? Maybe it could go through the screen stack and show the previous screen.

**Comment by Xerios** [comment]
`Hide()` already does this.

**Comment by hex** [comment]
It doesn't work for a specific case. I modified the *Simple Test* scene for demonstrating the behavior.

Steps:
1. Open Window 2
2. Open Window 1
3. Open Window 2
4. Go Back button

[https://www.dropbox.com/s/hsd1b1qgy8eheuu/testCase.unitypackage?dl=0](https://www.dropbox.com/s/hsd1b1qgy8eheuu/testCase.unitypackage?dl=0)

**Comment by Xerios** [comment]
Your're right, that doesn't look right at all. I must've messed up somewhere, gonna try to fix it.

**Comment by hex** [comment]
I think it's related to the way that an element is removed from the list (screenQueue).
This is the stack state before I press go back:
![Initial state](https://i.imgur.com/yska3Pf.png)
and this is after I press go back:
![After state](https://i.imgur.com/2jpqT0G.png)
It seems that it removes the first instance of that window from that list.
`screenQueue.Remove(screenToKill)`

**Comment by Xerios** [comment]
Right when you sent me the message I stumbled upon that as well.

Making it remove the last one doesn't get rid of the problem though.

**Comment by Xerios** [comment]
I found the issue and pushed the fix. 

Thanks for notifying. This change might or might've not messed up hideCurrent functionality because I removed some strange looking code that looked really out of place, but I'm not sure though. I should've done some unit tests :'(

**Comment by hex** [comment]
I will let you know if I discover anything weird. Thanks for acting so promptly!

**Comment by Xerios** [comment]
I'll close this issue for now
